import './globals.css'
import Wrapper from '@/components/Wrapper'
import { Montserrat } from 'next/font/google'
import { getServerSession } from "next-auth";
import { authOptions } from './api/auth/[...nextauth]/options';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
            <Wrapper session={session}>
                <body className={`${montserrat.className} h-screen w-screen flex justify-center select-none`}>
                    {children}
                </body>
            </Wrapper>
        </html >
    )
}
