import './globals.css'
import Navbar from '@/components/Navbar'
import Provider from '@/components/Provider'
import { Montserrat } from 'next/font/google'
import { getServerSession } from "next-auth";
import { authOptions } from './api/auth/[...nextauth]/route';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
            <Provider session={session}>
                <body className={montserrat.className}>
                    <Navbar />
                    {children}
                </body>
            </Provider>
        </html >
    )
}
