import type { Metadata } from 'next'
import './globals.css'
import authOptions from '@/app/api/auth/[...nextauth]/options'
import { getServerSession } from 'next-auth'
import Wrapper from '@/components/Wrapper'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

    const session = await getServerSession(authOptions)

    return (
        <Wrapper session={session}>
            <html lang="en" className='w-full h-full'>
                <body className='w-full h-full'>{children}</body>
            </html>
        </Wrapper>
    )
}
